# Generated by Django 6.0.3 on 2026-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('class_a_capacity', models.PositiveIntegerField(default=20)),
                ('class_b_capacity', models.PositiveIntegerField(default=50)),
                ('class_c_capacity', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
